# Validates PR titles follow semantic commit convention for automated releases

name: PR Title Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  statuses: write

jobs:
  validate-title:
    name: Validate Semantic Title
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configuration
          requireScope: false
          disallowScopes: ~
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Allowed types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Custom scopes (optional)
          scopes: |
            cli
            core
            api
            ui
            deps
            config
            release