name: CI

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check Biome style
        run: npx @biomejs/biome ci .

      - name: TypeScript Check
        run: npx tsc --noEmit --skipLibCheck

      - name: Spellcheck
        run: npm run spellcheck

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration Tests
        env:
          DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
        #run: npm run test:integration
        run: npm run test:integration -- --testPathPatterns="MixedDependencies