name: Release

on:
  push:
    branches:
      - main
      - beta
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - beta

env:
  NODE_VERSION: '20'
  CI: true
  LOG_LEVEL: 'ERROR'

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Verify dependencies integrity
        run: npm audit signatures
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: Lint
        run: npx @biomejs/biome ci . --diagnostic-level=error

      - name: Type Check
        run: npx tsc --noEmit --skipLibCheck

      - name: Spellcheck
        run: npm run spellcheck -- --no-progress --no-summary

      - name: Unit Tests
        env:
          NODE_ENV: test
          LOG_LEVEL: ERROR
        run: npm run test:unit

      - name: Check for Integration Test Requirement
        id: check-integration
        run: |
          # Check if this release includes changes that require integration tests
          echo "Checking if integration tests are needed for this release..."
          
          # Get the commit range for this push
          if [ "${{ github.event_name }}" == "push" ]; then
            COMMIT_RANGE="${{ github.event.before }}..${{ github.event.after }}"
          else
            # For workflow_run, use the last 20 commits as a safe range
            COMMIT_RANGE="HEAD~20..HEAD"
          fi
          
          # Check for integration-relevant changes in the commit range
          if git diff --name-only $COMMIT_RANGE | grep -E "(src/Api/|src/DatoCmsSync.ts|src/cli|src/DatoBuilderCLI.ts|src/config/|tests/integration/|package\.json|jest\.config\.integration\.ts)" > /dev/null; then
            echo "integration-required=true" >> $GITHUB_OUTPUT
            echo "✅ Integration tests required - found relevant changes"
          else
            echo "integration-required=false" >> $GITHUB_OUTPUT
            echo "⏭️ Integration tests not required - no relevant changes detected"
          fi

      - name: Integration Tests (Release)
        if: steps.check-integration.outputs.integration-required == 'true'
        env:
          DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
          NODE_ENV: test
          LOG_LEVEL: ERROR
        run: |
          echo "🚀 Running integration tests for release validation..."
          npm run test:integration

      - name: Integration Tests Skipped
        if: steps.check-integration.outputs.integration-required == 'false'
        run: |
          echo "⏭️ Integration tests skipped for this release"
          echo "No integration-critical changes detected in this release."

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release